### ISSUE TITLE
Default tab width

### ISSUE THREAD

**Issue by IstoraMandiri** [somebee/sublime-imba#4]
I'm a 2 spaces per tab kind of guy, but despite setting `"tab_size": 2` in my user preferences `imba` files always have 4 spaces per tab when opened. 

Is there a setting I'm missing?

Cheers

**Comment by lukeed** [comment]
85% certain that Imba needs to be in tabs in order for the compiler to work, since it is indentation-based.

As for changing from a width of 4 to 2, make sure your 'Status Bar' is showing. "View: Toggle Status Bar" in the prompt. Then, in the lower right, see what the `tab width` is set to. 

Additionally, you can create a custom setting for the Imba language. From the menu:
- Sublime Text -> Preferences -> Settings - More -> Syntax Specific

then insert something like this & save:

``` json
{
    "extensions": [ "imba" ],
    "tab_size": 2,
    "translate_tabs_to_spaces": false
}
```

Pretty sure you have to restart Sublime before it takes effect...

Syntax-specific preferences overrule everything else, I believe.

**Comment by IstoraMandiri** [comment]
Perfect @lukeed  -- thanks for the help! Syntax Specific settings saved the day.
